export default {
  optionsPracticeArea: [
    { value: 'arbitration', label: 'Arbitration & Dispute Resolution' },
    { value: 'banking', label: 'Banking and Finance' },
    { value: 'competition', label: 'Competition' },
    { value: 'construction', label: 'Construction' },
    { value: 'corporate', label: 'Corporate' },
    { value: 'criminal', label: 'Criminal' },
    { value: 'employment', label: 'Employment' },
    { value: 'energy', label: 'Energy and Infrastructure' },
    { value: 'environmental', label: 'Environmental'},
    { value: 'family', label: 'Family' },
    { value: 'healthcare', label: 'Healthcare and Clinical Negligence' },
    { value: 'immigration', label: 'Immigration' },
    { value: 'insolvency', label: 'Insolvency' },
    { value: 'insurance', label: 'Insurance' },
    { value: 'intellectual', label: 'Intellectual Property' },
    { value: 'litigation', label: 'Litigation' },
    { value: 'media', label: 'Media' },
    { value: 'privacy', label: 'Privacy' },
    { value: 'property', label: 'Property' },
    { value: 'public', label: 'Public Sector' },
    { value: 'shipping', label: 'Shipping and Maritime' },
    { value: 'sports', label: 'Sports' },
    { value: 'tax', label: 'Tax' },
    { value: 'technology', label: 'Technology' },
    { value: 'wills', label: 'Wills, Trust and Probate' }
  ],
};
